feat: #13 disable working jobs and remove container for behat
#13

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,177 +39,178 @@ jobs:
           yarn run production
 
   # Step Quality Control
-  prettier:
-    if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
+  # prettier:
+  #   if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
 
-    needs: [install]
+  #   needs: [install]
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    container:
-      image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
+  #   container:
+  #     image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v2
 
-      - name: Cache artifacts dependencies
-        uses: actions/cache@v2
-        with:
-          path: |
-            .env
-            bootstrap
-            node_modules
-            public
-            vendor
-          key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
+  #     - name: Cache artifacts dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .env
+  #           bootstrap
+  #           node_modules
+  #           public
+  #           vendor
+  #         key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
 
-      - name: Check the CS with Prettier
-        run: prettier --check "resources/**/*.+(js|json|scss|sass|css|vue)" ".babelrc" "composer.json" "package.json" "webpack.mix.js"
+  #     - name: Check the CS with Prettier
+  #       run: prettier --check "resources/**/*.+(js|json|scss|sass|css|vue)" ".babelrc" "composer.json" "package.json" "webpack.mix.js"
 
-  php-cs-fixer:
-    if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
+  # php-cs-fixer:
+  #   if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
 
-    needs: [install]
+  #   needs: [install]
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    container:
-      image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
+  #   container:
+  #     image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v2
 
-      - name: Cache artifacts dependencies
-        uses: actions/cache@v2
-        with:
-          path: |
-            .env
-            bootstrap
-            node_modules
-            public
-            vendor
-          key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
+  #     - name: Cache artifacts dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .env
+  #           bootstrap
+  #           node_modules
+  #           public
+  #           vendor
+  #         key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
 
-      - name: Check the Code Style with PHP CS Fixer
-        run: |
-          rm -f .php_cs.cache || true
-          php-cs-fixer fix --config=.php_cs --dry-run --diff --using-cache=no
+  #     - name: Check the Code Style with PHP CS Fixer
+  #       run: |
+  #         rm -f .php_cs.cache || true
+  #         php-cs-fixer fix --config=.php_cs --dry-run --diff --using-cache=no
 
-  phpstan:
-    if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
+  # phpstan:
+  #   if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
 
-    needs: [install]
+  #   needs: [install]
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    container:
-      image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
+  #   container:
+  #     image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v2
 
-      - name: Cache artifacts dependencies
-        uses: actions/cache@v2
-        with:
-          path: |
-            .env
-            bootstrap
-            node_modules
-            public
-            vendor
-          key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
+  #     - name: Cache artifacts dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .env
+  #           bootstrap
+  #           node_modules
+  #           public
+  #           vendor
+  #         key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
 
-      - name: Check the code with PHPStan
-        run: php vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=2G
+  #     - name: Check the code with PHPStan
+  #       run: php vendor/bin/phpstan analyse -c phpstan.neon --memory-limit=2G
 
   # Tests
-  phpunit:
-    if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
+  # phpunit:
+  #   if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
 
-    needs: [prettier, php-cs-fixer, phpstan]
+  #   needs: [prettier, php-cs-fixer, phpstan]
 
-    runs-on: ubuntu-latest
+  #   runs-on: ubuntu-latest
 
-    container:
-      image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
+  #   container:
+  #     image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
 
-    services:
-      database:
-        image: registry.gitlab.com/kuroi-taiyo/docker-store/mysql:latest
-        env:
-          MYSQL_ROOT_PASSWORD: root
-          MYSQL_DATABASE: stanislaspoisson
-          MYSQL_USER: stanislaspoisson
-          MYSQL_PASSWORD: stanislaspoisson
-          REDIS_PORT: 6379
-      redis:
-        image: registry.gitlab.com/kuroi-taiyo/docker-store/redis:latest
-        env:
-          MYSQL_ROOT_PASSWORD: root
-          MYSQL_DATABASE: stanislaspoisson
-          MYSQL_USER: stanislaspoisson
-          MYSQL_PASSWORD: stanislaspoisson
-          REDIS_PORT: 6379
+  #   services:
+  #     database:
+  #       image: registry.gitlab.com/kuroi-taiyo/docker-store/mysql:latest
+  #       env:
+  #         MYSQL_ROOT_PASSWORD: root
+  #         MYSQL_DATABASE: stanislaspoisson
+  #         MYSQL_USER: stanislaspoisson
+  #         MYSQL_PASSWORD: stanislaspoisson
+  #         REDIS_PORT: 6379
+  #     redis:
+  #       image: registry.gitlab.com/kuroi-taiyo/docker-store/redis:latest
+  #       env:
+  #         MYSQL_ROOT_PASSWORD: root
+  #         MYSQL_DATABASE: stanislaspoisson
+  #         MYSQL_USER: stanislaspoisson
+  #         MYSQL_PASSWORD: stanislaspoisson
+  #         REDIS_PORT: 6379
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
+  #   # Steps represent a sequence of tasks that will be executed as part of the job
+  #   steps:
+  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
+  #     - uses: actions/checkout@v2
 
-      - name: Cache artifacts dependencies
-        uses: actions/cache@v2
-        with:
-          path: |
-            .env
-            bootstrap
-            node_modules
-            public
-            vendor
-          key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
+  #     - name: Cache artifacts dependencies
+  #       uses: actions/cache@v2
+  #       with:
+  #         path: |
+  #           .env
+  #           bootstrap
+  #           node_modules
+  #           public
+  #           vendor
+  #         key: dependencies-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/composer.lock') }}
 
-      - name: Check the code with PHPUnit
-        run: php -d memory_limit=2048M vendor/bin/phpunit --stderr
+  #     - name: Check the code with PHPUnit
+  #       run: php -d memory_limit=2048M vendor/bin/phpunit --stderr
 
-      - name: Upload artifacts failure
-        uses: actions/upload-artifact@v2
-        if: failure()
-        with:
-          name: "${{ github.action }}-${{ github.job }}-FAILED"
-          path: |
-            bootstrap/
-            public/
-            storage/
-            tests/
-            .env
-            npm-debug.log
-            yarn-error.log
-            .php_cs.cache
-            .phpunit.result.cache
-          retention-days: 1
+  #     - name: Upload artifacts failure
+  #       uses: actions/upload-artifact@v2
+  #       if: failure()
+  #       with:
+  #         name: "${{ github.action }}-${{ github.job }}-FAILED"
+  #         path: |
+  #           bootstrap/
+  #           public/
+  #           storage/
+  #           tests/
+  #           .env
+  #           npm-debug.log
+  #           yarn-error.log
+  #           .php_cs.cache
+  #           .phpunit.result.cache
+  #         retention-days: 1
 
   behat-passed:
     if: github.ref != 'refs/heads/release/**' || github.ref != 'refs/tags/**'
 
-    needs: [prettier, php-cs-fixer, phpstan]
+    # needs: [prettier, php-cs-fixer, phpstan]
+    needs: [install]
 
     runs-on: ubuntu-latest
 
-    container:
-      image: registry.gitlab.com/kuroi-taiyo/docker-store/dind:latest
+    # container:
+    #   image: registry.gitlab.com/kuroi-taiyo/docker-store/dind:latest
 
-    services:
-      docker:
-        image: registry.gitlab.com/kuroi-taiyo/docker-store/docker:latest
-        env:
-          COMPOSE_HTTP_TIMEOUT: 300
-          DOCKER_DRIVER: overlay2
-          DOCKER_TLS_CERTDIR: "/certs"
+    # services:
+    #   docker:
+    #     image: registry.gitlab.com/kuroi-taiyo/docker-store/docker:latest
+    #     env:
+    #       COMPOSE_HTTP_TIMEOUT: 300
+    #       DOCKER_DRIVER: overlay2
+    #       DOCKER_TLS_CERTDIR: "/certs"
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
